import { createServer } from 'node:http'
import { createHash, createHmac, randomUUID } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { extname, join, normalize, dirname } from 'node:path'

const root = process.cwd()
const dataFile = join(process.env.DUMAH_DATA_DIR || join(root, 'data'), 'shop.json')
const adminUser = process.env.ADMIN_USER || 'Freddy'
const passwordHash = process.env.ADMIN_PASSWORD_HASH || '8f9986d2e6e6f358c101069f5831bac6ae234b7899b0727847c70df192f766d0'
const sessionKey = process.env.SESSION_KEY || '3ce61449468b003059f8aaabe9db37bba04b813d9fa8b38c312603314209d92f'
const blank = () => ({ orders: [], views: [], settings: { notification_emails: '', telegram_chat_id: '', telegram_enabled: false, telegram_configured: false, tax_id: '', vat_rate: '19' } })
let writes = Promise.resolve()
const load = async () => { try { return { ...blank(), ...JSON.parse(await readFile(dataFile, 'utf8')) } } catch (e) { if (e.code === 'ENOENT') return blank(); throw e } }
const save = (data) => (writes = writes.then(async () => { await mkdir(dirname(dataFile), { recursive: true }); await writeFile(dataFile, JSON.stringify(data, null, 2)) }))
const send = (res, status, value, headers = {}) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...headers }); res.end(JSON.stringify(value)) }
const input = (req) => new Promise((resolve) => { let raw = ''; req.on('data', c => raw += c); req.on('end', () => { try { resolve(JSON.parse(raw || '{}')) } catch { resolve({}) } }) })
const cookies = (req) => Object.fromEntries((req.headers.cookie || '').split(';').flatMap(p => { const i = p.indexOf('='); if (i < 1) return []; try { return [[decodeURIComponent(p.slice(0, i).trim()), decodeURIComponent(p.slice(i + 1))]] } catch { return [] } }))
const sign = (value) => createHmac('sha256', sessionKey).update(value).digest('hex')
const authorized = (req) => { const [user, expires, signature] = (cookies(req).dumah_admin || '').split('.'); return user === adminUser && Number(expires) >= Date.now() && signature === sign(`${user}.${expires}`) }

async function api(req, res, url) {
  const data = await load()
  if (url.pathname === '/api/admin/login' && req.method === 'POST') { const b = await input(req); if (b.username !== adminUser || createHash('sha256').update(String(b.password || '')).digest('hex') !== passwordHash) return send(res, 401, { error: 'Benutzername oder Passwort ist falsch.' }); const expires = Date.now() + 28800000, value = `${adminUser}.${expires}`; return send(res, 200, { ok: true }, { 'set-cookie': `dumah_admin=${encodeURIComponent(`${value}.${sign(value)}`)}; Max-Age=28800; Path=/; HttpOnly; Secure; SameSite=Strict` }) }
  if (url.pathname === '/api/admin/logout' && req.method === 'POST') return send(res, 200, { ok: true }, { 'set-cookie': 'dumah_admin=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Strict' })
  if (url.pathname === '/api/admin/dashboard' && req.method === 'GET') { if (!authorized(req)) return send(res, 401, { error: 'Nicht autorisiert' }); const pages = {}, days = {}, visitors = new Set(); for (const v of data.views) { pages[v.path] = (pages[v.path] || 0) + 1; const d = days[v.day] ||= { day: v.day, views: 0, visitors: new Set() }; d.views++; d.visitors.add(v.visitor_id); visitors.add(v.visitor_id) } return send(res, 200, { orders: data.orders.slice(0, 100), totals: { orders: data.orders.length, revenue_cents: data.orders.reduce((n,o)=>n+o.total_cents,0), visitors: visitors.size, views: data.views.length }, pages: Object.entries(pages).map(([path,views])=>({path,views})), daily: Object.values(days).map(d=>({day:d.day,views:d.views,visitors:d.visitors.size})).slice(-14), settings: { ...data.settings, mail_configured: Boolean(process.env.RESEND_API_KEY && process.env.MAIL_FROM) } }) }
  if (url.pathname === '/api/admin/settings' && req.method === 'PUT') { if (!authorized(req)) return send(res, 401, { error: 'Nicht autorisiert' }); Object.assign(data.settings, await input(req)); data.settings.telegram_configured ||= Boolean(data.settings.telegram_token); delete data.settings.telegram_token; await save(data); return send(res, 200, { ok: true, telegram_configured: data.settings.telegram_configured }) }
  if (url.pathname === '/api/admin/telegram/test') return send(res, 400, { error: 'Telegram-Test ist auf diesem Server noch nicht konfiguriert.' })
  if (url.pathname === '/api/analytics/view' && req.method === 'POST') { const b = await input(req), visitor = cookies(req).dumah_visitor || randomUUID(); data.views.push({ day: new Date().toISOString().slice(0,10), path: String(b.path || '/').slice(0,120), visitor_id: visitor }); await save(data); return send(res, 200, { ok: true }, cookies(req).dumah_visitor ? {} : { 'set-cookie': `dumah_visitor=${visitor}; Max-Age=31536000; Path=/; SameSite=Lax; Secure` }) }
  if (url.pathname === '/api/orders' && req.method === 'POST') { const b = await input(req), required = ['first','last','email','street','zip','city','country','size','shipping']; if (required.some(k=>!String(b[k]||'').trim())) return send(res,400,{error:'Unvollständige Bestelldaten'}); const id=`DE-${Date.now().toString(36).toUpperCase()}-${randomUUID().slice(0,4).toUpperCase()}`; data.orders.unshift({id,created_at:new Date().toISOString(),customer_name:`${b.first} ${b.last}`,email:b.email,address:`${b.street}, ${b.zip} ${b.city}`,country:b.country,size:b.size,shipping:b.shipping,total_cents:b.shipping==='express'?8989:7999,status:'payment_pending',invoice_number:'',tracking_number:'',shipped_at:'',canceled_at:''}); await save(data); return send(res,201,{ok:true,id,status:'payment_pending'}) }
  if (url.pathname === '/api/order-status') { const o=data.orders.find(x=>x.id===String(url.searchParams.get('order')||'').toUpperCase()); return o?send(res,200,{order:o.id,created_at:o.created_at,status:o.status,shipping:o.shipping,tracking_number:o.tracking_number,shipped_at:o.shipped_at,canceled_at:o.canceled_at}):send(res,404,{error:'Zu dieser Bestellnummer wurde keine Bestellung gefunden.'}) }
  const match=url.pathname.match(/^\/api\/admin\/orders\/([^/]+)\/([^/]+)$/); if(match&&req.method==='POST'){if(!authorized(req))return send(res,401,{error:'Nicht autorisiert'});const o=data.orders.find(x=>x.id===decodeURIComponent(match[1]));if(!o)return send(res,404,{error:'Bestellung nicht gefunden'});const b=await input(req),action=match[2];o.status={confirm:'confirmed',invoice:'confirmed',ship:'shipped',cancel:'canceled'}[action]||o.status;if(action==='invoice')o.invoice_number||=`RE-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;if(action==='ship'){o.tracking_number=String(b.tracking||'');o.shipped_at=new Date().toISOString()}if(action==='cancel')o.canceled_at=new Date().toISOString();await save(data);return send(res,200,{ok:true,status:o.status})}
  return send(res, 404, { error: 'Not found' })
}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'}
async function staticFile(res,url){if(!url.pathname.endsWith('/')&&['admin','checkout','status','impressum','datenschutz','agb','widerruf'].includes(url.pathname.slice(1))){res.writeHead(301,{location:`${url.pathname}/${url.search}`});return res.end()}const rel=url.pathname.endsWith('/')?`${url.pathname}index.html`:url.pathname;const file=normalize(join(root,decodeURIComponent(rel)));if(!file.toLowerCase().startsWith(root.toLowerCase()))return send(res,403,{error:'Forbidden'});try{const content=await readFile(file);res.writeHead(200,{'content-type':types[extname(file)]||'application/octet-stream'});res.end(content)}catch(e){if(e.code==='ENOENT')return send(res,404,{error:'Not found'});throw e}}
createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);return url.pathname.startsWith('/api/')?await api(req,res,url):await staticFile(res,url)}catch(e){console.error(e);send(res,500,{error:'Der Server konnte die Anfrage nicht verarbeiten.'})}}).listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('DUMAH server ready'))
