import './checkout.css'
import campaignBack from './assets/hoodie-campaign-back.png'

const product = { name: 'Nobody Said It Was Easy', price: 79.99 }
const money = value => new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(value)
const step = document.body.dataset.step
const order = JSON.parse(sessionStorage.getItem('dumah_order') || '{"size":"M","shipping":"standard"}')
const customer = JSON.parse(sessionStorage.getItem('dumah_customer') || '{}')
const shippingPrice = order.shipping === 'express' ? 9.9 : 0

const steps = `<nav class="steps" aria-label="Checkout Fortschritt"><span class="${step==='information'?'current':''} ${step!=='information'?'done':''}">01 Information</span><i></i><span class="${step==='shipping'?'current':''} ${step==='payment'?'done':''}">02 Versand</span><i></i><span class="${step==='payment'?'current':''}">03 Zahlung</span></nav>`
const summary = `<aside class="summary"><button class="summary-toggle" type="button">Bestellübersicht <span>${money(product.price+shippingPrice)}　⌄</span></button><div class="summary-inner"><div class="item"><div class="thumb"><img src="${campaignBack}" alt="${product.name}"><b>1</b></div><div><strong>${product.name}</strong><span>Object 001 · Größe ${order.size}</span><small>Limited 01—50</small></div><em>${money(product.price)}</em></div><dl><div><dt>Zwischensumme</dt><dd>${money(product.price)}</dd></div><div><dt>Versand</dt><dd>${shippingPrice ? money(shippingPrice) : 'Kostenlos'}</dd></div><div class="total"><dt>Gesamt <small>inkl. MwSt.</small></dt><dd><small>EUR</small> ${money(product.price+shippingPrice)}</dd></div></dl><div class="trust"><span>Authentifiziert</span><span>Handmade in Germany</span><span>50 Pieces</span></div></div></aside>`

const info = `<section class="checkout-content"><span class="label">Checkout / Information</span><h1>Wohin dürfen<br>wir liefern?</h1><form id="info-form" novalidate><label class="wide">E-Mail<input name="email" type="email" autocomplete="email" required value="${customer.email||''}"></label><label>Vorname<input name="first" autocomplete="given-name" required value="${customer.first||''}"></label><label>Nachname<input name="last" autocomplete="family-name" required value="${customer.last||''}"></label><label class="wide">Straße und Hausnummer<input name="street" autocomplete="street-address" required value="${customer.street||''}"></label><label>Postleitzahl<input name="zip" inputmode="numeric" autocomplete="postal-code" required value="${customer.zip||''}"></label><label>Ort<input name="city" autocomplete="address-level2" required value="${customer.city||''}"></label><label class="wide">Land<select name="country"><option>Deutschland</option><option>Österreich</option><option>Schweiz</option><option>Andere EU</option></select></label><button class="primary" type="submit">Weiter zum Versand <span>→</span></button><p class="error" role="alert"></p></form></section>`
const ship = `<section class="checkout-content"><span class="label">Checkout / Versand</span><h1>Wie schnell<br>soll es ankommen?</h1><div class="contact-card"><div><span>Kontakt</span><b>${customer.email||'—'}</b><a href="/checkout/">Ändern</a></div><div><span>Lieferadresse</span><b>${customer.street||'—'}, ${customer.zip||''} ${customer.city||''}</b><a href="/checkout/">Ändern</a></div></div><form id="shipping-form"><label class="delivery ${order.shipping==='standard'?'selected':''}"><input type="radio" name="shipping" value="standard" ${order.shipping==='standard'?'checked':''}><span><b>DHL Standard</b><small>2–4 Werktage · versichert</small></span><strong>Kostenlos</strong></label><label class="delivery ${order.shipping==='express'?'selected':''}"><input type="radio" name="shipping" value="express" ${order.shipping==='express'?'checked':''}><span><b>DHL Express</b><small>1–2 Werktage · versichert</small></span><strong>9,90 €</strong></label><div class="actions"><a href="/checkout/">← Zurück</a><button class="primary" type="submit">Weiter zur Zahlung <span>→</span></button></div></form></section>`
const pay = `<section class="checkout-content"><span class="label">Checkout / Zahlung</span><h1>Sicher<br>abschließen.</h1><div class="contact-card"><div><span>Kontakt</span><b>${customer.email||'—'}</b><a href="/checkout/">Ändern</a></div><div><span>Versand</span><b>${order.shipping==='express'?'DHL Express · 9,90 €':'DHL Standard · Kostenlos'}</b><a href="/checkout/shipping.html">Ändern</a></div></div><form id="payment-form"><fieldset><legend>Zahlungsmethode</legend><label class="payment selected"><input type="radio" name="payment" value="card" checked><span><b>Kredit- oder Debitkarte</b><small>Visa · Mastercard · Amex</small></span><i>••••</i></label><label class="payment"><input type="radio" name="payment" value="paypal"><span><b>PayPal</b><small>Weiterleitung zu PayPal</small></span><i>PP</i></label><label class="payment"><input type="radio" name="payment" value="klarna"><span><b>Klarna</b><small>Sofort oder später bezahlen</small></span><i>K</i></label></fieldset><div class="gateway-note">Die Zahlungsoberfläche ist vorbereitet. Für Live-Zahlungen muss ein Zahlungsanbieter verbunden werden.</div><div class="actions"><a href="/checkout/shipping.html">← Zurück</a><button class="primary" type="submit">${money(product.price+shippingPrice)} sicher bezahlen <span>→</span></button></div></form><p class="error" role="alert"></p></section>`

document.querySelector('#checkout').innerHTML = `<header class="checkout-header"><a class="back-shop" href="/">← Shop</a><a class="logo" href="/">DUMAH<small>EDITION</small></a><span>Secure checkout</span></header>${steps}<main>${step==='information'?info:step==='shipping'?ship:pay}${summary}</main><footer><span>© 2026 DUMAH EDITION</span><div><a href="#">Datenschutz</a><a href="#">AGB</a><a href="#">Impressum</a></div></footer>`

document.querySelector('.summary-toggle').addEventListener('click', e => e.currentTarget.closest('.summary').classList.toggle('open'))
document.querySelectorAll('input[type="radio"]').forEach(input => input.addEventListener('change', () => { document.querySelectorAll(`input[name="${input.name}"]`).forEach(i=>i.closest('label').classList.toggle('selected',i.checked)) }))
if(step==='information') document.querySelector('#info-form').addEventListener('submit', e => { e.preventDefault(); if(!e.currentTarget.checkValidity()){e.currentTarget.reportValidity();document.querySelector('.error').textContent='Bitte fülle alle Pflichtfelder aus.';return} sessionStorage.setItem('dumah_customer',JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))));location.href='/checkout/shipping.html' })
if(step==='shipping') document.querySelector('#shipping-form').addEventListener('submit', e => { e.preventDefault();order.shipping=new FormData(e.currentTarget).get('shipping');sessionStorage.setItem('dumah_order',JSON.stringify(order));location.href='/checkout/payment.html' })
if(step==='payment') document.querySelector('#payment-form').addEventListener('submit', e => { e.preventDefault();document.querySelector('.error').textContent='Für echte Zahlungen muss Stripe, Shopify Payments oder PayPal angebunden werden.' })
