import './style.css'
import hoodieBack from './assets/hoodie-back.png'
import hoodieFront from './assets/hoodie-front.png'
const products=[['NOBODY SAID HOODIE','HOODIE / 01','€280'],['OBSIDIAN FLIGHT','BOMBER / 02','€280'],['VOID CARGO 01','TROUSERS / 03','€195']]
document.querySelector('#app').innerHTML=`
<div class="noise"></div><div class="bar">COMPLIMENTARY EU SHIPPING — EDITION 01 AVAILABLE NOW</div>
<header><a class="logo" href="#top"><svg viewBox="0 0 48 48"><path d="M6 7h14c14 0 22 7 22 17S34 41 20 41H6V7Zm10 8v18h4c7 0 12-3 12-9s-5-9-12-9h-4Z"/></svg><b>DUMAH<small>EDITION</small></b></a><nav><a href="#collection">SHOP</a><a href="#manifesto">MANIFESTO</a><a href="#archive">ARCHIVE</a></nav><div class="actions"><button class="bag">BAG <span>(0)</span></button><button class="menu" aria-label="Menü"><i></i><i></i></button></div></header>
<main id="top"><section class="hero"><div class="hero-photo"><img src="${hoodieFront}" alt="DUMAH Nobody Said Hoodie Frontansicht"></div><div class="hero-sigil" aria-hidden="true">D</div><div class="hero-ring" aria-hidden="true"></div><div class="shade"></div><div class="coords"><span>PRIVATE RELEASE / 001</span><span>BERLIN — AW 26</span></div><div class="hero-copy"><p>THE FIRST OBJECT — DUMAH 001</p><h1>NOBODY<br><em>SAID.</em></h1><a class="cta" href="#collection">ENTER OBJECT 001 <b>↗</b></a></div><div class="vertical">EACH PIECE INDIVIDUALLY NUMBERED</div><a class="scroll" href="#collection">DISCOVER　↓</a></section>
<section class="collection" id="collection"><div class="section-head reveal"><div><span>[ PRIVATE RELEASE ]</span><h2>OBJECTS</h2></div><p>The first DUMAH object.<br>Individually numbered and never reproduced.</p><small>OBJECT 001 / WORLDWIDE</small></div><div class="grid">${products.map((p,i)=>`<article class="product reveal ${i===0?'featured':''}" data-id="${i}"><button class="inspect" aria-label="${p[0]} ansehen"><div class="pic piece-${i+1}">${i===0?`<div class="hoodie-pair"><img class="hoodie-back" src="${hoodieBack}" alt="DUMAH Hoodie Rückenansicht"><img class="hoodie-front" src="${hoodieFront}" alt="DUMAH Hoodie Frontansicht"></div>`:`<div class="piece-code">D/0${i+1}</div><div class="piece-form" aria-hidden="true"></div>`}<small>${i===0?'OBJECT 001 — FIRST RELEASE':'UNRELEASED OBJECT'}</small><span class="enter">${i===0?'ENTER OBJECT':'CLASSIFIED'}　↗</span></div><div class="info"><div><small>${p[1]}　/　${i===0?'PRIVATE RELEASE':'LOCKED'}</small><h3>${p[0]}</h3><span class="availability">${i===0?'AVAILABLE BY PRIVATE RELEASE':'NOT YET REVEALED'}</span></div><b>${i===0?p[2]:'—'}</b></div></button></article>`).join('')}</div></section>
<section class="provenance"><div><small>01</small><span>DESIGNED</span><b>BERLIN</b></div><div><small>02</small><span>PRODUCTION</span><b>27 / FORM</b></div><div><small>03</small><span>AUTHENTICATION</span><b>SERIALIZED</b></div><div><small>04</small><span>REISSUE</span><b>NEVER</b></div></section>
<section class="manifesto" id="manifesto"><div class="ghost">D</div><div class="statement reveal"><small>[ THE CODE ]</small><p>WE DON'T DESIGN FOR<br>THE PRESENT. <em>WE SHAPE</em><br><em>WHAT COMES AFTER.</em></p><a href="#archive">READ THE MANIFESTO ↗</a></div><div class="origin">DUMAH / דומה<br>THE ANGEL OF SILENCE</div></section>
<section class="archive" id="archive"><div class="archive-art" aria-hidden="true"><span>D</span><i></i></div><article class="reveal"><small>[ ARCHIVE / 00 ]</small><h2>THE<br>SILENCE<br>BEFORE.</h2><p>A study in protection, restraint and the architecture of movement.</p><a class="cta" href="#top">VIEW THE EDITION <b>↗</b></a></article></section></main>
<footer><a href="#top">DUMAH<sup>®</sup></a><div>INSTAGRAM　 CONTACT　 LEGAL</div><small>© 2026 DUMAH EDITION<br>BERLIN, DE</small></footer>
<div class="backdrop"></div><aside aria-hidden="true"><button class="close">×</button><small>[ YOUR SELECTION ]</small><h2>BAG <sup>0</sup></h2><div class="cart"><p>YOUR BAG IS EMPTY.<br>THE EDITION IS WAITING.</p></div><div class="checkout"><div>SUBTOTAL <b>€0</b></div><button>PROCEED TO CHECKOUT　↗</button></div></aside><div class="piece-view" aria-hidden="true"><button class="piece-close" aria-label="Schließen">×</button><div class="piece-stage piece-real"><div class="real-stage"><img src="${hoodieBack}" alt="Nobody Said Hoodie Rückseite"><img src="${hoodieFront}" alt="Nobody Said Hoodie Vorderseite"></div><span>FRONT / BACK　—　OBJECT 001</span></div><div class="piece-panel"><small>[ PRIVATE OBJECT / <span class="panel-index">01</span> ]</small><h2>NOBODY SAID HOODIE</h2><p>Heavy washed black. DUMAH signature at the heart. A singular back artwork built around defiance, value and the refusal to explain.</p><dl><div><dt>EDITION</dt><dd>01 OF 27</dd></div><div><dt>OBJECT</dt><dd>DUMAH 001</dd></div><div><dt>REISSUE</dt><dd>NEVER</dd></div></dl><label>SELECT SIZE</label><div class="sizes"><button>S</button><button class="selected">M</button><button>L</button><button>XL</button></div><button class="acquire">ACQUIRE OBJECT <b>€280</b></button><small class="concierge">PRIVATE CONCIERGE INCLUDED　/　COMPLIMENTARY DELIVERY</small></div></div>`

const cart=[],drawer=document.querySelector('aside'),backdrop=document.querySelector('.backdrop')
function openCart(open){drawer.classList.toggle('open',open);backdrop.classList.toggle('open',open);drawer.setAttribute('aria-hidden',!open);document.body.classList.toggle('locked',open)}
document.querySelector('.bag').onclick=()=>openCart(true);document.querySelector('.close').onclick=()=>openCart(false);backdrop.onclick=()=>openCart(false);document.addEventListener('keydown',e=>e.key==='Escape'&&openCart(false))
const view=document.querySelector('.piece-view');let activeProduct=0
function openPiece(id){if(id>0)return;activeProduct=id;view.classList.add('open');view.setAttribute('aria-hidden','false');document.body.classList.add('locked')}
function closePiece(){view.classList.remove('open');view.setAttribute('aria-hidden','true');document.body.classList.remove('locked')}
document.querySelectorAll('.inspect').forEach(btn=>btn.onclick=e=>openPiece(+e.currentTarget.closest('.product').dataset.id));document.querySelector('.piece-close').onclick=closePiece
document.querySelectorAll('.sizes button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.sizes button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')})
document.querySelector('.acquire').onclick=()=>{let p=products[activeProduct],size=document.querySelector('.sizes .selected').textContent;cart.push([...p,size]);document.querySelector('.bag span').textContent=`(${cart.length})`;drawer.querySelector('h2 sup').textContent=cart.length;drawer.querySelector('.checkout b').textContent=`€${cart.reduce((s,x)=>s+ +x[2].slice(1),0)}`;drawer.querySelector('.cart').innerHTML=cart.map((x,i)=>`<div class="line"><div class="cart-code">D/0${i+1}</div><div><small>${x[1]}</small><b>${x[0]}</b><span>SIZE ${x[3]} / ${x[2]}</span></div></div>`).join('');closePiece();openCart(true)}
const menu=document.querySelector('.menu');menu.onclick=()=>{menu.classList.toggle('active');document.querySelector('nav').classList.toggle('active')};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.querySelector('nav').classList.remove('active'))
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x))
